FROM ubuntu

RUN apt-get update && \
	apt-get update -qq && \
  	apt-get install -y --only-upgrade autoconf && \
  	apt-get install -y --only-upgrade automake && \
  	apt-get install -y --only-upgrade autotools-dev && \
  	apt-get install -y autoconf-archive && \
	apt-get install -y binutils build-essential && \
    apt-get install -y libboost-dev && \
    apt-get install -y libboost-python-dev && \
    apt-get install -y python && \ 
    apt-get install -y python-pip python-dev